// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: backup.proto

package mihonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         []*BackupManga         `protobuf:"bytes,1,rep,name=manga,proto3" json:"manga,omitempty"`
	Categories    []*BackupCategory      `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Sources       []*BackupSource        `protobuf:"bytes,101,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetManga() []*BackupManga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *Backup) GetCategories() []*BackupCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Backup) GetSources() []*BackupSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type BackupManga struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Source             int64                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Url                string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist             *string                `protobuf:"bytes,4,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	Author             *string                `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Description        *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Genre              []string               `protobuf:"bytes,7,rep,name=genre,proto3" json:"genre,omitempty"`
	Status             int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	ThumbnailUrl       *string                `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	DateAdded          int64                  `protobuf:"varint,13,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	Viewer             int32                  `protobuf:"varint,14,opt,name=viewer,proto3" json:"viewer,omitempty"`
	Chapters           []*BackupChapter       `protobuf:"bytes,16,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Categories         []int64                `protobuf:"varint,17,rep,packed,name=categories,proto3" json:"categories,omitempty"`
	Tracking           []*BackupTracking      `protobuf:"bytes,18,rep,name=tracking,proto3" json:"tracking,omitempty"`
	Favorite           bool                   `protobuf:"varint,100,opt,name=favorite,proto3" json:"favorite,omitempty"`
	ChapterFlags       int32                  `protobuf:"varint,101,opt,name=chapter_flags,json=chapterFlags,proto3" json:"chapter_flags,omitempty"`
	ViewerFlags        *int32                 `protobuf:"varint,103,opt,name=viewer_flags,json=viewerFlags,proto3,oneof" json:"viewer_flags,omitempty"`
	History            []*BackupHistory       `protobuf:"bytes,104,rep,name=history,proto3" json:"history,omitempty"`
	UpdateStrategy     int32                  `protobuf:"varint,105,opt,name=update_strategy,json=updateStrategy,proto3" json:"update_strategy,omitempty"`
	LastModifiedAt     int64                  `protobuf:"varint,106,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	FavoriteModifiedAt *int64                 `protobuf:"varint,107,opt,name=favorite_modified_at,json=favoriteModifiedAt,proto3,oneof" json:"favorite_modified_at,omitempty"`
	ExcludedScanlators []string               `protobuf:"bytes,108,rep,name=excluded_scanlators,json=excludedScanlators,proto3" json:"excluded_scanlators,omitempty"`
	Version            int64                  `protobuf:"varint,109,opt,name=version,proto3" json:"version,omitempty"`
	Notes              string                 `protobuf:"bytes,110,opt,name=notes,proto3" json:"notes,omitempty"`
	Initialized        bool                   `protobuf:"varint,111,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	mi := &file_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupManga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupManga) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *BackupManga) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *BackupManga) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BackupManga) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *BackupManga) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupManga) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetDateAdded() int64 {
	if x != nil {
		return x.DateAdded
	}
	return 0
}

func (x *BackupManga) GetViewer() int32 {
	if x != nil {
		return x.Viewer
	}
	return 0
}

func (x *BackupManga) GetChapters() []*BackupChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *BackupManga) GetCategories() []int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BackupManga) GetTracking() []*BackupTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *BackupManga) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *BackupManga) GetChapterFlags() int32 {
	if x != nil {
		return x.ChapterFlags
	}
	return 0
}

func (x *BackupManga) GetViewerFlags() int32 {
	if x != nil && x.ViewerFlags != nil {
		return *x.ViewerFlags
	}
	return 0
}

func (x *BackupManga) GetHistory() []*BackupHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackupManga) GetUpdateStrategy() int32 {
	if x != nil {
		return x.UpdateStrategy
	}
	return 0
}

func (x *BackupManga) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupManga) GetFavoriteModifiedAt() int64 {
	if x != nil && x.FavoriteModifiedAt != nil {
		return *x.FavoriteModifiedAt
	}
	return 0
}

func (x *BackupManga) GetExcludedScanlators() []string {
	if x != nil {
		return x.ExcludedScanlators
	}
	return nil
}

func (x *BackupManga) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupManga) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *BackupManga) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type BackupChapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scanlator      *string                `protobuf:"bytes,3,opt,name=scanlator,proto3,oneof" json:"scanlator,omitempty"`
	Read           bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	Bookmark       bool                   `protobuf:"varint,5,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	LastPageRead   int64                  `protobuf:"varint,6,opt,name=last_page_read,json=lastPageRead,proto3" json:"last_page_read,omitempty"`
	DateFetch      int64                  `protobuf:"varint,7,opt,name=date_fetch,json=dateFetch,proto3" json:"date_fetch,omitempty"`
	DateUpload     int64                  `protobuf:"varint,8,opt,name=date_upload,json=dateUpload,proto3" json:"date_upload,omitempty"`
	ChapterNumber  float32                `protobuf:"fixed32,9,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	SourceOrder    int64                  `protobuf:"varint,10,opt,name=source_order,json=sourceOrder,proto3" json:"source_order,omitempty"`
	LastModifiedAt int64                  `protobuf:"varint,11,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	Version        int64                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupChapter) Reset() {
	*x = BackupChapter{}
	mi := &file_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChapter) ProtoMessage() {}

func (x *BackupChapter) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChapter.ProtoReflect.Descriptor instead.
func (*BackupChapter) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupChapter) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupChapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupChapter) GetScanlator() string {
	if x != nil && x.Scanlator != nil {
		return *x.Scanlator
	}
	return ""
}

func (x *BackupChapter) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *BackupChapter) GetBookmark() bool {
	if x != nil {
		return x.Bookmark
	}
	return false
}

func (x *BackupChapter) GetLastPageRead() int64 {
	if x != nil {
		return x.LastPageRead
	}
	return 0
}

func (x *BackupChapter) GetDateFetch() int64 {
	if x != nil {
		return x.DateFetch
	}
	return 0
}

func (x *BackupChapter) GetDateUpload() int64 {
	if x != nil {
		return x.DateUpload
	}
	return 0
}

func (x *BackupChapter) GetChapterNumber() float32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *BackupChapter) GetSourceOrder() int64 {
	if x != nil {
		return x.SourceOrder
	}
	return 0
}

func (x *BackupChapter) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupChapter) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BackupCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Order         int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Flags         int64                  `protobuf:"varint,100,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCategory) Reset() {
	*x = BackupCategory{}
	mi := &file_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCategory) ProtoMessage() {}

func (x *BackupCategory) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCategory.ProtoReflect.Descriptor instead.
func (*BackupCategory) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupCategory) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *BackupCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackupCategory) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type BackupTracking struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SyncId              int32                  `protobuf:"varint,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	LibraryId           int64                  `protobuf:"varint,2,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	MediaIdInt          int32                  `protobuf:"varint,3,opt,name=media_id_int,json=mediaIdInt,proto3" json:"media_id_int,omitempty"`
	TrackingUrl         string                 `protobuf:"bytes,4,opt,name=tracking_url,json=trackingUrl,proto3" json:"tracking_url,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	LastChapterRead     float32                `protobuf:"fixed32,6,opt,name=last_chapter_read,json=lastChapterRead,proto3" json:"last_chapter_read,omitempty"`
	TotalChapters       int32                  `protobuf:"varint,7,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Score               float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Status              int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	StartedReadingDate  int64                  `protobuf:"varint,10,opt,name=started_reading_date,json=startedReadingDate,proto3" json:"started_reading_date,omitempty"`
	FinishedReadingDate int64                  `protobuf:"varint,11,opt,name=finished_reading_date,json=finishedReadingDate,proto3" json:"finished_reading_date,omitempty"`
	Private             bool                   `protobuf:"varint,12,opt,name=private,proto3" json:"private,omitempty"`
	MediaId             int64                  `protobuf:"varint,100,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupTracking) Reset() {
	*x = BackupTracking{}
	mi := &file_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupTracking) ProtoMessage() {}

func (x *BackupTracking) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupTracking.ProtoReflect.Descriptor instead.
func (*BackupTracking) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupTracking) GetSyncId() int32 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *BackupTracking) GetLibraryId() int64 {
	if x != nil {
		return x.LibraryId
	}
	return 0
}

func (x *BackupTracking) GetMediaIdInt() int32 {
	if x != nil {
		return x.MediaIdInt
	}
	return 0
}

func (x *BackupTracking) GetTrackingUrl() string {
	if x != nil {
		return x.TrackingUrl
	}
	return ""
}

func (x *BackupTracking) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupTracking) GetLastChapterRead() float32 {
	if x != nil {
		return x.LastChapterRead
	}
	return 0
}

func (x *BackupTracking) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *BackupTracking) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BackupTracking) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupTracking) GetStartedReadingDate() int64 {
	if x != nil {
		return x.StartedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetFinishedReadingDate() int64 {
	if x != nil {
		return x.FinishedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *BackupTracking) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type BackupHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LastRead      int64                  `protobuf:"varint,2,opt,name=last_read,json=lastRead,proto3" json:"last_read,omitempty"`
	ReadDuration  int64                  `protobuf:"varint,3,opt,name=read_duration,json=readDuration,proto3" json:"read_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupHistory) Reset() {
	*x = BackupHistory{}
	mi := &file_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHistory) ProtoMessage() {}

func (x *BackupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHistory.ProtoReflect.Descriptor instead.
func (*BackupHistory) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupHistory) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupHistory) GetLastRead() int64 {
	if x != nil {
		return x.LastRead
	}
	return 0
}

func (x *BackupHistory) GetReadDuration() int64 {
	if x != nil {
		return x.ReadDuration
	}
	return 0
}

type BackupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSource) Reset() {
	*x = BackupSource{}
	mi := &file_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSource) ProtoMessage() {}

func (x *BackupSource) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSource.ProtoReflect.Descriptor instead.
func (*BackupSource) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSource) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

var File_backup_proto protoreflect.FileDescriptor

const file_backup_proto_rawDesc = "" +
	"\n" +
	"\fbackup.proto\x12\x0fmihon.backup.v1\"\xb6\x01\n" +
	"\x06Backup\x122\n" +
	"\x05manga\x18\x01 \x03(\v2\x1c.mihon.backup.v1.BackupMangaR\x05manga\x12?\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1f.mihon.backup.v1.BackupCategoryR\n" +
	"categories\x127\n" +
	"\asources\x18e \x03(\v2\x1d.mihon.backup.v1.BackupSourceR\asources\"\xe8\a\n" +
	"\vBackupManga\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x03R\x06source\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\x06artist\x18\x04 \x01(\tH\x00R\x06artist\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x01R\x06author\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05genre\x18\a \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12(\n" +
	"\rthumbnail_url\x18\t \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"date_added\x18\r \x01(\x03R\tdateAdded\x12\x16\n" +
	"\x06viewer\x18\x0e \x01(\x05R\x06viewer\x12:\n" +
	"\bchapters\x18\x10 \x03(\v2\x1e.mihon.backup.v1.BackupChapterR\bchapters\x12\x1e\n" +
	"\n" +
	"categories\x18\x11 \x03(\x03R\n" +
	"categories\x12;\n" +
	"\btracking\x18\x12 \x03(\v2\x1f.mihon.backup.v1.BackupTrackingR\btracking\x12\x1a\n" +
	"\bfavorite\x18d \x01(\bR\bfavorite\x12#\n" +
	"\rchapter_flags\x18e \x01(\x05R\fchapterFlags\x12&\n" +
	"\fviewer_flags\x18g \x01(\x05H\x04R\vviewerFlags\x88\x01\x01\x128\n" +
	"\ahistory\x18h \x03(\v2\x1e.mihon.backup.v1.BackupHistoryR\ahistory\x12'\n" +
	"\x0fupdate_strategy\x18i \x01(\x05R\x0eupdateStrategy\x12(\n" +
	"\x10last_modified_at\x18j \x01(\x03R\x0elastModifiedAt\x125\n" +
	"\x14favorite_modified_at\x18k \x01(\x03H\x05R\x12favoriteModifiedAt\x88\x01\x01\x12/\n" +
	"\x13excluded_scanlators\x18l \x03(\tR\x12excludedScanlators\x12\x18\n" +
	"\aversion\x18m \x01(\x03R\aversion\x12\x14\n" +
	"\x05notes\x18n \x01(\tR\x05notes\x12 \n" +
	"\vinitialized\x18o \x01(\bR\vinitializedB\t\n" +
	"\a_artistB\t\n" +
	"\a_authorB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_thumbnail_urlB\x0f\n" +
	"\r_viewer_flagsB\x17\n" +
	"\x15_favorite_modified_at\"\x8a\x03\n" +
	"\rBackupChapter\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tscanlator\x18\x03 \x01(\tH\x00R\tscanlator\x88\x01\x01\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x1a\n" +
	"\bbookmark\x18\x05 \x01(\bR\bbookmark\x12$\n" +
	"\x0elast_page_read\x18\x06 \x01(\x03R\flastPageRead\x12\x1d\n" +
	"\n" +
	"date_fetch\x18\a \x01(\x03R\tdateFetch\x12\x1f\n" +
	"\vdate_upload\x18\b \x01(\x03R\n" +
	"dateUpload\x12%\n" +
	"\x0echapter_number\x18\t \x01(\x02R\rchapterNumber\x12!\n" +
	"\fsource_order\x18\n" +
	" \x01(\x03R\vsourceOrder\x12(\n" +
	"\x10last_modified_at\x18\v \x01(\x03R\x0elastModifiedAt\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversionB\f\n" +
	"\n" +
	"_scanlator\"`\n" +
	"\x0eBackupCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05flags\x18d \x01(\x03R\x05flags\"\xbf\x03\n" +
	"\x0eBackupTracking\x12\x17\n" +
	"\async_id\x18\x01 \x01(\x05R\x06syncId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x01(\x03R\tlibraryId\x12 \n" +
	"\fmedia_id_int\x18\x03 \x01(\x05R\n" +
	"mediaIdInt\x12!\n" +
	"\ftracking_url\x18\x04 \x01(\tR\vtrackingUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12*\n" +
	"\x11last_chapter_read\x18\x06 \x01(\x02R\x0flastChapterRead\x12%\n" +
	"\x0etotal_chapters\x18\a \x01(\x05R\rtotalChapters\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x120\n" +
	"\x14started_reading_date\x18\n" +
	" \x01(\x03R\x12startedReadingDate\x122\n" +
	"\x15finished_reading_date\x18\v \x01(\x03R\x13finishedReadingDate\x12\x18\n" +
	"\aprivate\x18\f \x01(\bR\aprivate\x12\x19\n" +
	"\bmedia_id\x18d \x01(\x03R\amediaId\"c\n" +
	"\rBackupHistory\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tlast_read\x18\x02 \x01(\x03R\blastRead\x12#\n" +
	"\rread_duration\x18\x03 \x01(\x03R\freadDuration\"?\n" +
	"\fBackupSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceIdB1Z/tsunagu/backend/internal/backup/mihonpb;mihonpbb\x06proto3"

var (
	file_backup_proto_rawDescOnce sync.Once
	file_backup_proto_rawDescData []byte
)

func file_backup_proto_rawDescGZIP() []byte {
	file_backup_proto_rawDescOnce.Do(func() {
		file_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)))
	})
	return file_backup_proto_rawDescData
}

var file_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_backup_proto_goTypes = []any{
	(*Backup)(nil),         // 0: mihon.backup.v1.Backup
	(*BackupManga)(nil),    // 1: mihon.backup.v1.BackupManga
	(*BackupChapter)(nil),  // 2: mihon.backup.v1.BackupChapter
	(*BackupCategory)(nil), // 3: mihon.backup.v1.BackupCategory
	(*BackupTracking)(nil), // 4: mihon.backup.v1.BackupTracking
	(*BackupHistory)(nil),  // 5: mihon.backup.v1.BackupHistory
	(*BackupSource)(nil),   // 6: mihon.backup.v1.BackupSource
}
var file_backup_proto_depIdxs = []int32{
	1, // 0: mihon.backup.v1.Backup.manga:type_name -> mihon.backup.v1.BackupManga
	3, // 1: mihon.backup.v1.Backup.categories:type_name -> mihon.backup.v1.BackupCategory
	6, // 2: mihon.backup.v1.Backup.sources:type_name -> mihon.backup.v1.BackupSource
	2, // 3: mihon.backup.v1.BackupManga.chapters:type_name -> mihon.backup.v1.BackupChapter
	4, // 4: mihon.backup.v1.BackupManga.tracking:type_name -> mihon.backup.v1.BackupTracking
	5, // 5: mihon.backup.v1.BackupManga.history:type_name -> mihon.backup.v1.BackupHistory
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_backup_proto_init() }
func file_backup_proto_init() {
	if File_backup_proto != nil {
		return
	}
	file_backup_proto_msgTypes[1].OneofWrappers = []any{}
	file_backup_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backup_proto_goTypes,
		DependencyIndexes: file_backup_proto_depIdxs,
		MessageInfos:      file_backup_proto_msgTypes,
	}.Build()
	File_backup_proto = out.File
	file_backup_proto_goTypes = nil
	file_backup_proto_depIdxs = nil
}
